spring.main.allow-bean-definition-overriding=true

# Tip: It's recommended to use `application-private.properties` for sensitive information like API keys.

## 1. browser settings

# GUI, HEADLESS
# browser.display.mode=GUI

## LLM settings

# uncomment to use openrouter provider
#openrouter.api.key=sk-or-v1-4dc7deeffde81f7dcd1b0b778af10ee3546dedebbcea6d01bcf834412bc63
#openrouter.model.name=openai/gpt-5.4
#openrouter.base.url=https://openrouter.ai/api/v1/

#openrouter.api.key=sk-or-v1-4dc7deeffde81f7dcd1b0b77ab0ee3546542cfdebbcea6d01bcf834412bc63
#openrouter.model.name=bytedance-seed/seed-2.0-lite
#openrouter.base.url=https://openrouter.ai/api/v1/

# uncomment to use volcengine provider (bytedance)
# volcengine.api.key=3a96bd5a-65f6-44f9-ade4-c2e5de622d4a
# volcengine.model.name=doubao-seed-2-0-pro-260215
# volcengine.base.url=https://ark.cn-beijing.volces.com/api/v3

# uncomment to use the official deepseek provider
#deepseek.api.key=sk-1234567890

# uncomment to use the openai compatible provider
# openai.api.key=sk-1234567890
# openai.model.name=gpt-4o
# openai.base.url=https://api.openai.com/v1

# aliyun qwen on dashscope
# openai.api.key=sk-sk-9c68ec4f197e47b7be30132e3ae2fd9e
# openai.model.name=qwen-plus
# openai.base.url=https://dashscope.aliyuncs.com/compatible-mode/v1


# other predefined LLM models - docs/config/llm/llm-config.md
