package ai.platon.pulsar.agentic.model

import ai.platon.browser4.driver.chrome.dom.model.MergedDOMTreeNode
import ai.platon.pulsar.agentic.ActResult
import ai.platon.pulsar.agentic.ObserveResult
import ai.platon.pulsar.common.Strings
import ai.platon.pulsar.common.compactedBrief
import ai.platon.pulsar.common.llmFriendlyBrief
import ai.platon.pulsar.common.serialize.json.Pson
import ai.platon.pulsar.external.ModelResponse
import com.fasterxml.jackson.annotation.JsonIgnore
import com.fasterxml.jackson.annotation.JsonIncludeProperties
import org.apache.commons.lang3.StringUtils
import java.time.Instant

data class DetailedActResult(
    val actionDescription: ActionDescription,
    val toolCallResult: ToolCallResult? = null,
    val success: Boolean = false,
    /**
     * A short description about the current state
     * */
    val description: String? = null,
    /**
     * The exception that not from tool call execution which is already in ToolCallResult
     * */
    val exception: Exception? = null,
) {
    fun toActResult(): ActResult {
        return ActResult(
            action = actionDescription.instruction,
            success = success,
            message = description ?: "",
            result = toolCallResult,
            detail = this
        )
    }

    fun toJson(): String {
        return Pson.toJson(this)
    }

    override fun toString(): String {
        return "DetailedActResult(success=$success, description=$description, exception=${exception?.compactedBrief()}, actionDescription=${actionDescription}, toolCallResult=${toolCallResult})"
    }

    companion object {
        fun failed(actionDescription: ActionDescription, exception: Exception? = null): DetailedActResult {
            return DetailedActResult(actionDescription, exception = exception)
        }
    }
}

data class ToolSpec constructor(
    val domain: String,
    val method: String,
    val arguments: List<Arg> = listOf(),
    val returnType: String = "Unit",
    val description: String? = null,
    val help: String? = null,
) {
    data class Arg(
        val name: String,
        val type: String,
        val defaultValue: String? = null,
    ) {
        @get:JsonIgnore
        val expression: String
            get() {
                return if (defaultValue != null) "$name: $type = $defaultValue" else "$name: $type"
            }
    }

    @get:JsonIgnore
    val expression: String
        get() {
            val args = arguments.joinToString(prefix = "(", postfix = ")")
            return "$domain.$method$args"
        }
}

/**
 * @property domain The tool domain (aka namespace), e.g. "tab", "fs", "skill.blog", or a custom domain.
 * @property method The tool method to call, e.g. "click", "writeString", "extract", etc.
 * @property arguments The arguments for the tool call, as a map of argument name to value. The types of the values are not strictly defined, and may be converted to strings when passed to the tool executor. The tool executor should be responsible for parsing the arguments according to the tool specification.
 * @property description An optional description for this tool call, which can be used for better understanding the purpose of the tool call, and can be included in the prompt for better explainability. The description should be concise and informative, and can be generated by the agent based on the context and the tool call itself.
 * */
data class ToolCall constructor(
    val domain: String,
    val method: String,
    val arguments: MutableMap<String, Any?> = mutableMapOf(),
    val description: String? = null,
) {
    @get:JsonIgnore
    val weakTypeNamedArguments
        get() = arguments.entries.joinToString { (k, v) -> "$k=" + Strings.doubleQuote(v?.toString()) }

    @get:JsonIgnore
    val pseudoNamedArguments
        get() = arguments.entries
            .joinToString { (k, v) -> "$k=" + Strings.doubleQuote(Strings.compactInline(v?.toString(), 20)) }

    @get:JsonIgnore
    val cliOptions
        get() = arguments.entries
            .joinToString { (k, v) -> "--$k=" + Strings.doubleQuote(Strings.compactInline(v?.toString(), 20)) }

    @get:JsonIgnore
    val weakTypeExpression: String get() = "$domain.${method}($weakTypeNamedArguments)"

    /**
     * The pseudo expression, which is used for LLM and messages
     * */
    @get:JsonIgnore
    val pseudoExpression: String get() = "$domain.${method}($pseudoNamedArguments)"

    override fun toString() = pseudoExpression
}

/**
 * @property expression The original expression that caused the exception, which can be used for better understanding the context of the exception, and can be included in the prompt for better explainability. The expression should be concise and informative, and can be generated by the agent based on the context and the exception itself.
 * @property cause The original exception that caused the error, which can be used for better understanding the details of the error, and can be included in the prompt for better explainability. The cause should be the original exception thrown by the tool executor, and can be used to extract the message and other relevant information for the error.
 * @property help An optional help message for this exception, which can be used for better understanding how to fix the error, and can be included in the prompt for better explainability. The help message should be concise and informative, and can be generated by the agent based on the context and the exception itself, or can be provided by the tool executor based on the tool specification and the error details.
 * */
data class TcException(
    val expression: String = "",
    @JsonIgnore
    val cause: Exception? = null,
    var help: String? = null,
) {
    val domain: String get() = expression.substringBefore('.')
    val method: String get() = StringUtils.substringBetween(expression, ".", ")")
    val message: String? get() = cause?.llmFriendlyBrief()

    override fun toString(): String {
        return "Exception when call tool: $expression, cause: $message, help: $help"
    }
}

data class TcEvaluate constructor(
    /**
     * Ignore the value in preview, which may cause recursion when the value is complex and contains a lot of data.
     * The preview should be generated from the expression and description, which is more concise and informative.
     * */
    @JsonIgnore
    val value: Any? = null,
    val description: String? = null,
    val className: String? = null,
    val expression: String? = null,
    var exception: TcException? = null
) {
    constructor(expression: String, cause: Exception, help: String? = null) :
            this(expression = expression, exception = TcException(expression, cause, help))

    override fun toString(): String {
        return doGetPreview()
    }

    private fun doGetPreview(): String {
        return when (value) {
            is Number,
            is Boolean -> "$value"
            is String -> Strings.compactInline(value, 50)
            else -> mapOf(
                "description" to description, "expression" to expression,
                "className" to className, "exception" to exception?.message
            ).filterValues { it != null }.entries.joinToString { (k, v) -> "$k=$v" }
        }
    }

    companion object {
        /**
         * No Operation
         * */
        val NO_OP = TcEvaluate()
    }
}

data class ToolCallResult constructor(
    val evaluate: TcEvaluate,
    val message: String? = null,
    @JsonIgnore
    val actionDescription: ActionDescription? = null
) {
    val success: Boolean get() = evaluate.exception != null
    val expression: String get() = actionDescription?.expression ?: ""
    val modelResponse: String? get() = actionDescription?.modelResponse?.content

    companion object {
        /**
         * No Operation
         * */
        val NO_OP = ToolCallResult(TcEvaluate.NO_OP, "Noop")
    }
}

data class ObserveElement constructor(
    val modelResponse: String? = null,

    // the DOM node locator, format is `frameIndex,backendNodeId`
    val ref: String? = null,

    val screenshotContentSummary: String? = null,
    val currentPageContentSummary: String? = null,
    val evaluationPreviousGoal: String? = null,
    val nextGoal: String? = null,
    val thinking: String? = null,

    // Revised fields
    val toolCall: ToolCall? = null,
    @JsonIgnore
    val node: MergedDOMTreeNode? = null,
    val backendNodeId: Int? = null,
    val xpath: String? = null,
    val cssSelector: String? = null,
    val cssFriendlyExpression: String? = null,
) {
    @get:JsonIgnore
    val description: String? get() = toolCall?.description

    @get:JsonIgnore
    val domain: String? get() = toolCall?.domain

    @get:JsonIgnore
    val method: String? get() = toolCall?.method

    @get:JsonIgnore
    val arguments: Map<String, Any?>? get() = toolCall?.arguments

    /**
     * Expression with weak parameter types
     * */
    @get:JsonIgnore
    val expression: String? get() = toolCall?.weakTypeExpression

    @get:JsonIgnore
    val pseudoExpression get() = toolCall?.pseudoExpression
}

@JsonIncludeProperties("states")
data class AgentHistory(
    val states: MutableList<AgentState> = mutableListOf(),
) {
    val size get() = states.size

    val finalResult get() = states.lastOrNull()
    val isDone get() = finalResult?.isComplete == true
    val isSuccess get() = finalResult?.isSuccess == true
    val totalSteps get() = states.size
    val hasErrors get() = states.any { it.hasErrors }

    val actionHistory get() = states.map { it.actionDescription }
    val actionResults get() = states.map { it.toolCallResult }

    val urls get() = states.map { it.url }
    val modelOutputs get() = states.map { it.actionDescription?.modelResponse?.content }
    val modelThoughts get() = states.map { it.actionDescription?.observeElement?.thinking }

    fun isEmpty() = states.isEmpty()
    fun isNotEmpty() = states.isNotEmpty()
    fun first() = states.first()
    fun last() = states.last()
    fun firstOrNull() = states.firstOrNull()
    fun lastOrNull() = states.lastOrNull()

    override fun toString(): String {
        return states.joinToString("\n") { it.toString() }
    }
}

/**
 * The action description for the agent to go forward in the next step.
 * */
data class ActionDescription constructor(
    /**
     * The user's original instruction, should be only one instruction for the whole session, and should not be
     * changed in different steps. The reason is that we want to keep the original instruction as the main goal
     * of the session, and use the step and event to track the progress.
     * If we change the instruction in different steps, it may cause confusion and make it harder to track the progress.
     * */
    val instruction: String,

    /**
     * AI: observe elements
     * */
    val observeElements: List<ObserveElement>? = null,

    /**
     * AI: whether the task is complete
     * */
    var isComplete: Boolean = false,
    /**
     * AI: the error cause for the task
     * */
    var errorCause: String? = null,
    /**
     * AI: a summary about this task
     * */
    var summary: String? = null,
    /**
     * AI: a summary about this task
     * */
    val keyFindings: List<String>? = null,
    /**
     * AI: next suggestions
     * */
    val nextSuggestions: List<String>? = null,
    /**
     * AI: model response
     * */
    val modelResponse: ModelResponse? = null,
    /**
     * The exception if any
     * */
    val exception: Exception? = null,
    /**
     * The execution context
     * */
    val context: Any? = null,
    /**
     * The agent state
     * */
    val agentState: AgentState? = null,
) {
    val observeElement: ObserveElement? get() = observeElements?.firstOrNull()
    val toolCall: ToolCall? get() = observeElement?.toolCall
    val locator: String? get() = observeElement?.ref
    val xpath: String? get() = observeElement?.xpath

    /**
     * Expression with weak parameter types
     * */
    val expression: String? get() = observeElement?.expression
    val cssFriendlyExpression: String? get() = observeElement?.cssFriendlyExpression
    val pseudoExpression: String? get() = observeElement?.pseudoExpression

    val isReallyComplete get() = isComplete || expression?.contains("agent.done") == true

    fun complete(summary: String? = null) {
        isComplete = true
        if (summary != null) {
            this.summary = summary
        }
    }

    fun toActionDescriptions(): List<ActionDescription> {
        val elements = observeElements ?: return emptyList()
        return elements.map { this.copy(observeElements = listOf(it)) }
    }

    fun toObserveResults(agentState: AgentState): List<ObserveResult> {
        val results = observeElements?.map { ele ->
            ObserveResult(
                locator = ele.ref,
                domain = ele.domain?.ifBlank { null },
                method = ele.method?.ifBlank { null },
                arguments = ele.arguments?.takeIf { it.isNotEmpty() },
                description = ele.description ?: "(No comment ...)",

                screenshotContentSummary = ele.screenshotContentSummary,
                currentPageContentSummary = ele.currentPageContentSummary,
                evaluationPreviousGoal = ele.evaluationPreviousGoal,
                nextGoal = ele.nextGoal,
                thinking = ele.thinking,

                backendNodeId = ele.backendNodeId,
                observeElement = ele,
                agentState = agentState,
                actionDescription = this,
            )
        }

        return results ?: emptyList()
    }

    fun toJson(): String {
        return Pson.toJson(
            mapOf(
                "instruction" to instruction,
                "isComplete" to isComplete,
                "errorCause" to errorCause,
                "summary" to summary,
                "keyFindings" to keyFindings,
                "nextSuggestions" to nextSuggestions,
                "modelResponse" to modelResponse?.content,
                "exception" to exception?.compactedBrief(),
            )
        )
    }

    override fun toString(): String {
        return if (isComplete) "Completed. Summary: $summary"
        else (cssFriendlyExpression ?: modelResponse?.toString() ?: "")
    }
}

data class ProcessTrace constructor(
    val step: Int,
    val event: String? = null,
    val method: String? = null,
    val agentState: String? = null,
    val expression: String? = null,
    val isComplete: Boolean = false,
    val tcEvalResult: String? = null,
    val message: String? = null,
    val items: Map<String, Any?> = emptyMap(),
    val timestamp: Instant = Instant.now(),
) {
    fun toJson(): String {
        return Pson.toJson(this)
    }

    override fun toString(): String {
        fun format(v: Any?): String? {
            return when (v) {
                null -> null
                is Throwable -> v.compactedBrief()
                else -> Strings.compactInline(v.toString(), 50)
            }
        }

        val itemStr = items.entries.joinToString { (k, v) -> "$k=" + format(v) }.takeIf { it.isNotBlank() }

        val str = buildString {
            append(timestamp)

            append(" | step=$step")
            event?.let { append(", event=$event") }
            method?.let { append(", method=$method") }

            if (!itemStr.isNullOrBlank()) {
                append("\n    $itemStr")
            }
            if (!message.isNullOrBlank()) {
                append("\n    $message")
            }
            if (!agentState.isNullOrBlank()) {
                append("\n    $agentState")
            }
        }

        return str
    }
}
